#!/bin/bash

# This script assumes it is positioned in dotfiles directory.

DOT_DIR=$( cd $(dirname $0) ; pwd -P ) # absolute path to dotfiles directory
HOME_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"

COLOR_NONE='\e[0m'
COLOR_BROWN='\e[0;33m'
COLOR_RED='\e[0;31m'

# Takes source and target and creates link if it does not exist.
install_link() {
    local s=$1
    local t=$2

    # if correct link exists
    if [[ -L $t && $(readlink -f $t) == $(readlink -f $s) ]]; then
        echo -e "${COLOR_BROWN}Skipping, correct link already exists ($t -> $s) ${COLOR_NONE}"
        return 0
    fi

    mkdir -p "$(dirname "$t")"
    ln --symbolic --no-target-directory --interactive --verbose $s $t
}

echo "== Installing dotfiles =="

echo -e "\nInstalling .emacs.d:"
install_link $DOT_DIR/vanilla-emacs.d $HOME/.emacs.d

echo -e "\nInstalling .vimrc:"
install_link $DOT_DIR/vimrc $HOME/.vimrc

echo -e "\nInstalling login session configuration files:"
install_link $DOT_DIR/profile $HOME/.profile
install_link $DOT_DIR/bash/bash_profile $HOME/.bash_profile
install_link $DOT_DIR/bash/bashrc $HOME/.bashrc
install_link $DOT_DIR/bash/bash_aliases $HOME/.bash_aliases
if [ ! -e $HOME/.bashrc_local ]; then
    echo "# Put bash settings specific for this machine here. Loaded by .bashrc" \
        > $HOME/.bashrc_local
    echo "$HOME/.bashrc_local created. Put machine specific bash settings here!"
fi

echo -e "\nInstalling git configuration files:"
install_link $DOT_DIR/git/git-completion.bash $HOME/.git-completion.bash
install_link $DOT_DIR/git/git-prompt.sh $HOME/.git-prompt.sh
install_link $DOT_DIR/git/gitconfig $HOME/.gitconfig
which delta &>/dev/null || echo -e "${COLOR_RED}WARNING: 'delta' is not installed, but we use it in ~/.gitconfig as custom pager/diff. On Arch Linux you can install it with 'pacman -S git-delta'.${COLOR_NONE}"
install_link $DOT_DIR/git/gitignore $HOME/.gitignore

echo -e "\nInstalling Ghostty config:"
install_link $DOT_DIR/ghostty/config $HOME_CONFIG/ghostty/config

echo -e "\n== Installation finished! =="
